# Generated by Django 6.1 on 2026-08-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('under-investigation', 'Under investigation'),
                    ('rejected', 'Rejected'),
                    ('resolved', 'Resolved'),
                ],
                default='pending',
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.CharField(
                choices=[('red-flag', 'Red flag'), ('intervention', 'Intervention')],
                default='red-flag',
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='records',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
